package com.example.zd_x.faceverification.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.zd_x.faceverification.mvp.model.CompareResultsBean;
import com.example.zd_x.faceverification.mvp.model.HistoryVerificationResultModel;

import com.example.zd_x.faceverification.dao.CompareResultsBeanDao;
import com.example.zd_x.faceverification.dao.HistoryVerificationResultModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig compareResultsBeanDaoConfig;
    private final DaoConfig historyVerificationResultModelDaoConfig;

    private final CompareResultsBeanDao compareResultsBeanDao;
    private final HistoryVerificationResultModelDao historyVerificationResultModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        compareResultsBeanDaoConfig = daoConfigMap.get(CompareResultsBeanDao.class).clone();
        compareResultsBeanDaoConfig.initIdentityScope(type);

        historyVerificationResultModelDaoConfig = daoConfigMap.get(HistoryVerificationResultModelDao.class).clone();
        historyVerificationResultModelDaoConfig.initIdentityScope(type);

        compareResultsBeanDao = new CompareResultsBeanDao(compareResultsBeanDaoConfig, this);
        historyVerificationResultModelDao = new HistoryVerificationResultModelDao(historyVerificationResultModelDaoConfig, this);

        registerDao(CompareResultsBean.class, compareResultsBeanDao);
        registerDao(HistoryVerificationResultModel.class, historyVerificationResultModelDao);
    }
    
    public void clear() {
        compareResultsBeanDaoConfig.clearIdentityScope();
        historyVerificationResultModelDaoConfig.clearIdentityScope();
    }

    public CompareResultsBeanDao getCompareResultsBeanDao() {
        return compareResultsBeanDao;
    }

    public HistoryVerificationResultModelDao getHistoryVerificationResultModelDao() {
        return historyVerificationResultModelDao;
    }

}
